#! /bin/sh

xsetroot -cursor_name left_ptr
sxhkd &


bspc monitor -d 1 2 3 4 5 6 7 8


bspc config border_width	2
bspc config focused_border_color \#cccccc
bspc config normal_border_color \#18181B
bspc config window_gap		12
bspc config focus_follows_pointer false


#bspc rule -a Opera follow=on focus=on desktop=2
#bspc rule -a ArmCord follow=on focus=on desktop=4
#bspc rule -a TelegramDesktop follow=on focus=on desktop=4


feh --bg-fill ~/wp/wp0.jpg

sleep 0.3

setxkbmap -layout us,ru -variant ,, -option 'grp:alt_shift_toggle'

killall polybar
sleep 0.1
$HOME/.polybar/launch.sh &

killall picom
sleep 0.1
picom --config $HOME/.config/picom/picom.conf &

killall greenclip
sleep 0.1
greenclip daemon &

#$HOME/scripts/low-battery-notification &
#sh $HOME/scripts/autostart.sh &
#bash $HOME/scripts/templogger.sh &

